version: '3.8'

x-services-volume:
  &services-volume
  type: bind
  source: ./static/output_models
  target: workspace/static/output_models

services:
  gfedntm-dev:
    image: nemesis1303/gfedntm
    container_name: gfedntm-server
    restart: always
    tty: true
    ports:
      - 8887:8887
    networks:
      - gfedntm_network
    volumes:
      - gfedntm-dev-volume:/workspace

  gfedntm-server:
    image: nemesis1303/gfedntm
    container_name: gfedntm-server
    #restart: always
    command: python3 workspace/main.py --min_clients_federation 2 --model_type avitm
    tty: true
    ports:
      - 8888:8888
    networks:
      - gfedntm_network
    volumes:
      - ./static/output_models:/workspace/static/output_models/server

  gfedntm-client1:
    image: nemesis1303/gfedntm
    container_name: gfedntm-client1
    #restart: always
    command: python3 workspace/main.py --id 1 --source workspace/static/datasets/synthetic2.npz #--source workspace/static/datasets/preprocessing_example/s2cs_tiny_preproc.parquet --data_type real --fos computer_science #
    tty: true
    ports:
      - 8889:8889
    networks:
      - gfedntm_network
    volumes:
      - ./static/output_models:/workspace/static/output_models/client1

  gfedntm-client2:
    image: nemesis1303/gfedntm
    container_name: gfedntm-client2
    #restart: always
    command: python3 workspace/main.py --id 2 --source workspace/static/datasets/synthetic2.npz #--source workspace/static/datasets/preprocessing_example/s2cs_tiny_preproc.parquet --data_type real --fos economics 
    tty: true
    ports:
      - 8810:8810
    networks:
      - gfedntm_network
    volumes:
      - ./static/output_models:/workspace/static/output_models/client2
  
  gfedntm-client3:
    image: nemesis1303/gfedntm
    container_name: gfedntm-client3
    restart: always
    command: python3 workspace/main.py --id 3 --source workspace/static/datasets/synthetic2.npz
    #command: python3 workspace/main.py --id 3 #--data_type real --fos sociology
    tty: true
    ports:
      - 8811:8811
    networks:
      - gfedntm_network
    volumes:
      - ./static/output_models:/workspace/static/output_models

  gfedntm-client4:
    image: nemesis1303/gfedntm
    container_name: gfedntm-client4
    restart: always
    command: python3 workspace/main.py --id 4 --source workspace/static/datasets/synthetic2.npz
    #command: python3 workspace/main.py --id 4 #--data_type real --fos philosophy
    tty: true
    ports:
      - 8812:8812
    networks:
      - gfedntm_network
    volumes:
      - ./static/output_models:/workspace/static/output_models
  
  gfedntm-client5:
    image: nemesis1303/gfedntm
    container_name: gfedntm-client5
    restart: always
    command: python3 workspace/main.py --id 25 --source workspace/static/datasets/synthetic2.npz
    #command: python3 workspace/main.py --id 5 #--data_type real --fos political_science
    tty: true
    ports:
      - 8813:8813
    networks:
      - gfedntm_network
    volumes:
      - ./static/output_models:/workspace/static/output_models

networks:
  gfedntm_network:
    driver: bridge

volumes:
  gfedntm-dev-volume:
