# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos import federated_pb2 as federated__pb2


class FederationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendLocalTensor = channel.unary_unary(
                '/federated.Federation/sendLocalTensor',
                request_serializer=federated__pb2.ClientTensorRequest.SerializeToString,
                response_deserializer=federated__pb2.ServerReceivedResponse.FromString,
                )
        self.sendAggregatedTensor = channel.unary_unary(
                '/federated.Federation/sendAggregatedTensor',
                request_serializer=federated__pb2.Empty.SerializeToString,
                response_deserializer=federated__pb2.ServerAggregatedTensorRequest.FromString,
                )
        self.upload = channel.stream_unary(
                '/federated.Federation/upload',
                request_serializer=federated__pb2.Chunk.SerializeToString,
                response_deserializer=federated__pb2.Reply.FromString,
                )
        self.download = channel.unary_stream(
                '/federated.Federation/download',
                request_serializer=federated__pb2.Empty.SerializeToString,
                response_deserializer=federated__pb2.Chunk.FromString,
                )
        self.sendLocalDic = channel.unary_unary(
                '/federated.Federation/sendLocalDic',
                request_serializer=federated__pb2.Dictionary.SerializeToString,
                response_deserializer=federated__pb2.Reply.FromString,
                )
        self.sendGlobalDicAndInitialNN = channel.unary_unary(
                '/federated.Federation/sendGlobalDicAndInitialNN',
                request_serializer=federated__pb2.Empty.SerializeToString,
                response_deserializer=federated__pb2.FeatureUnion.FromString,
                )


class FederationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendLocalTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendAggregatedTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendLocalDic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendGlobalDicAndInitialNN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendLocalTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.sendLocalTensor,
                    request_deserializer=federated__pb2.ClientTensorRequest.FromString,
                    response_serializer=federated__pb2.ServerReceivedResponse.SerializeToString,
            ),
            'sendAggregatedTensor': grpc.unary_unary_rpc_method_handler(
                    servicer.sendAggregatedTensor,
                    request_deserializer=federated__pb2.Empty.FromString,
                    response_serializer=federated__pb2.ServerAggregatedTensorRequest.SerializeToString,
            ),
            'upload': grpc.stream_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=federated__pb2.Chunk.FromString,
                    response_serializer=federated__pb2.Reply.SerializeToString,
            ),
            'download': grpc.unary_stream_rpc_method_handler(
                    servicer.download,
                    request_deserializer=federated__pb2.Empty.FromString,
                    response_serializer=federated__pb2.Chunk.SerializeToString,
            ),
            'sendLocalDic': grpc.unary_unary_rpc_method_handler(
                    servicer.sendLocalDic,
                    request_deserializer=federated__pb2.Dictionary.FromString,
                    response_serializer=federated__pb2.Reply.SerializeToString,
            ),
            'sendGlobalDicAndInitialNN': grpc.unary_unary_rpc_method_handler(
                    servicer.sendGlobalDicAndInitialNN,
                    request_deserializer=federated__pb2.Empty.FromString,
                    response_serializer=federated__pb2.FeatureUnion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.Federation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Federation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendLocalTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Federation/sendLocalTensor',
            federated__pb2.ClientTensorRequest.SerializeToString,
            federated__pb2.ServerReceivedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendAggregatedTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Federation/sendAggregatedTensor',
            federated__pb2.Empty.SerializeToString,
            federated__pb2.ServerAggregatedTensorRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/federated.Federation/upload',
            federated__pb2.Chunk.SerializeToString,
            federated__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/federated.Federation/download',
            federated__pb2.Empty.SerializeToString,
            federated__pb2.Chunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendLocalDic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Federation/sendLocalDic',
            federated__pb2.Dictionary.SerializeToString,
            federated__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendGlobalDicAndInitialNN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federated.Federation/sendGlobalDicAndInitialNN',
            federated__pb2.Empty.SerializeToString,
            federated__pb2.FeatureUnion.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
